### ISSUE TITLE
Error 255 while trying to install on Windwos 10 Pro x64

### ISSUE THREAD

**Issue by lluisclava** [fusioninventory/fusioninventory-agent-windows-installer#13]
When I try to install the agent on a Windwos 10 Pro x64 it fails the install process at the begging with error 255. I attach a screenshot of the error.

![Captura de pantalla 2022-08-29 a les 14 11 27](https://user-images.githubusercontent.com/1722057/187199239-b0849df8-37f9-4d3a-8e3b-7f4b630e53ad.png)

**Comment by ddurieux** [comment]
Seems it has uninstalled previous version.

Can you do uninstall the agent and then try again to install?

**Comment by lluisclava** [comment]
It's true. I tried with another computer and it works fine. I installed the glpi-agent and it works fine to.

Thanks for your answer.
