### ISSUE TITLE
Implement more reliable /runnow option

### ISSUE THREAD

**Issue by g-bougard** [fusioninventory/fusioninventory-agent-windows-installer#2]
Users often complains `/runnow` option does not work (see [fia #493](https://github.com/fusioninventory/fusioninventory-agent/issues/493) for example). Actually it is implemented as a task run which seems not reliable through windows versions.

**Comment by Wolvverine** [comment]
But #493 is installation issue only.
look on:
```
--delaytime=TIME
--lazy
--force  
--wait=LIMIT  
```

**Comment by g-bougard** [comment]
@vollkommenIrrelevant 
Regarding your [fia #493 issue](https://github.com/fusioninventory/fusioninventory-agent/issues/493), I still have a question. How can you be confident the `/runnow` option didn't work ?
Have you check in GLPI the "Last Contact" reported for a computer you just installed ?

**Comment by g-bougard** [comment]
Fixed in 2.4.2 release.
