### ISSUE TITLE
communication error: 400 Bad Request

### ISSUE THREAD

**Issue by proyectotau** [fusioninventory/fusioninventory-agent-windows-installer#3]
I've just installed successfully windows installer 2.4.1 using standard VBS script.

When Agent dumps to log file it shows this error:
```
[Fri Aug 17 11:43:32 2018][error] [http client] communication error: 400 Bad Request
[Fri Aug 17 11:43:32 2018][error] No answer from server at https://10.225.236.29/ocsinventory/
[...]
[Fri Aug 17 11:43:36 2018][error] [http client] communication error: 400 Bad Request
[Fri Aug 17 11:43:36 2018][error] No answer from server at http://10.225.204.18/ocsinventory/
```
Why? What needs Agent to communicate correctly? What am I doing bad?

PS:
Port 443 => `https://10.225.236.29/ocsinventory/` is OCS Server v2.4
Port 80 =>   `http://10.225.204.18/ocsinventory/` is OCS Server v2.0.1

This is my SetupOptions =`"/S /acceptlicense /add-firewall-exception /debug=2 /execmode=Service /httpd /httpd-port=65432 /httpd-trust='127.0.0.1/32,10.225.213.0/25' /installtasks=Full /logger=File /runnow /scan-homedirs /scan-profiles /server='https://10.225.236.29/ocsinventory/,http://10.225.204.18/ocsinventory/' /tag=tag-001 /delaytime=10"`

Thanks a lot in advance!!

**Comment by proyectotau** [comment]
Cont'ed:

![image](https://user-images.githubusercontent.com/24544980/44263173-34999880-a21e-11e8-9072-22a05d51e44d.png)

**Comment by g-bougard** [comment]
Hi @proyectotau 
this only means the agent got no answer from the server. This may have many reasons:

- this machine may not be authorized to access your servers
- the network may fail to route the request
- local firewall rule may block the agent requests: `/add-firewall-exception` option is still not implemented

Are you able to contact your servers from a browser on your 2 URLs and from this machine ?

**Comment by proyectotau** [comment]
Hi again. Thanks for your kind response.

Really agents do contact with servers:

> [Mon Aug 20 13:21:47 2018][error] [http client] communication error: 400 Bad Request
> [Mon Aug 20 13:21:47 2018][error] No answer from server at http://10.225.204.18/ocsinventory/

Apache's access log file:

> 10.225.213.43 - - [20/Aug/2018:13:21:47 +0200] "POST /ocsinventory/ HTTP/1.1" 400 305 "-" "FusionInventory-Agent_v2.4.1"

OCS Server is v2.0.1 ¿Is Fusion Inventory Agent compatible with it?

Server has OCS_OPT_EXT_USERAGENTS_FILE_PATH enabled and file contents:

>OCS-NG_WINDOWS_AGENT_v2.0.5.0
>OCS-NG_WINDOWS_AGENT_v2.0.5.2
>FusionInventory-Agent_v2.4
>FusionInventory-Agent_v2.4.1
>OCS-NG_unified_unix_agent_v2.0.5

¿Is this a valid conf? OCS Server v2.0.1 only acepts to OCS Agents :-(

**Comment by proyectotau** [comment]
I have also prove with OCS Server 2.4 where OCS_OPT_EXT_USERAGENTS_FILE_PATH seems, it's honored:

These are the results:

[Mon Aug 20 13:21:57 2018][debug] forking process 0 to handle task Maintenance
[Mon Aug 20 13:21:57 2018][info] running task Maintenance
[Mon Aug 20 13:21:59 2018][debug] Agent memory usage before freeing memory: -1
[Mon Aug 20 13:21:59 2018][info] FusionInventory Agent memory usage: -1
[Mon Aug 20 13:22:01 2018][debug] [http client] Using Compress::Zlib for compression
[Mon Aug 20 13:22:01 2018][info] sending prolog request to server server0
[Mon Aug 20 13:22:01 2018][debug2] [http client] sending message:

![image](https://user-images.githubusercontent.com/24544980/44339867-49c33100-a483-11e8-8800-489a1bf8a6a0.png)

[Mon Aug 20 13:22:02 2018][debug] forking process 0 to handle task NetInventory
[Mon Aug 20 13:22:02 2018][debug] NetInventory task execution not requested
[Mon Aug 20 13:22:05 2018][debug] forking process 0 to handle task Collect
[Mon Aug 20 13:22:05 2018][info] running task Collect
[Mon Aug 20 13:22:05 2018][debug2] http://10.225.236.29/ocsinventory/?action=getConfig&task[Collect]=2.4.0&machineid=MYCOMPUTER-MV-XP-2018-08-20-11-29-41
[Mon Aug 20 13:22:05 2018][error] [http client] communication error: 400 Bad Request
[Mon Aug 20 13:22:05 2018][info] No job schedule returned from server at http://10.225.236.29/ocsinventory/
[Mon Aug 20 13:22:07 2018][debug] forking process 0 to handle task WMI
[Mon Aug 20 13:22:10 2018][debug] forking process 0 to handle task NetDiscovery
[Mon Aug 20 13:22:10 2018][debug] NetDiscovery task execution not requested
[Mon Aug 20 13:22:13 2018][debug] forking process 0 to handle task Deploy
[Mon Aug 20 13:22:13 2018][info] running task Deploy
[Mon Aug 20 13:22:13 2018][debug2] http://10.225.236.29/ocsinventory/?action=getConfig&task[Deploy]=2.6&machineid=MYCOMPUTER-MV-XP-2018-08-20-11-29-41
[Mon Aug 20 13:22:13 2018][error] [http client] communication error: 400 Bad Request
[Mon Aug 20 13:22:13 2018][info] No job schedule returned from server at http://10.225.236.29/ocsinventory/
[Mon Aug 20 13:22:16 2018][debug] forking process 0 to handle task Inventory
[Mon Aug 20 13:22:16 2018][info] running task Inventory
[Mon Aug 20 13:22:16 2018][debug2] module FusionInventory::Agent::Task::Inventory::AIX disabled
...
REQUEST
...
/REQUEST
[Mon Aug 20 13:22:53 2018][debug2] format: Zlib
[Mon Aug 20 13:22:53 2018][debug2] [http client] receiving message:
xml version='1.0' encoding='UTF-8
REPLY
    RESPONSE NO_ACCOUNT_UPDATE /RESPONSE
/REPLY

Apache's access log file:

10.225.213.43 - - [20/Aug/2018:13:22:01 +0200] "POST /ocsinventory/ HTTP/1.1" 200 235 "-" "FusionInventory-Agent_v2.4.1"
10.225.213.43 - - [20/Aug/2018:13:22:05 +0200] "GET /ocsinventory/?action=getConfig&task[Collect]=2.4.0&machineid=MYCOMPUTER-MV-XP-2018-08-20-11-29-41 HTTP/1.1" 400 226 "-" "FusionInventory-Agent_v2.4.1"
10.225.213.43 - - [20/Aug/2018:13:22:13 +0200] "GET /ocsinventory/?action=getConfig&task[Deploy]=2.6&machineid=MYCOMPUTER-MV-XP-2018-08-20-11-29-41 HTTP/1.1" 400 226 "-" "FusionInventory-Agent_v2.4.1"
10.225.213.43 - - [20/Aug/2018:13:22:53 +0200] "POST /ocsinventory/ HTTP/1.1" 200 91 "-" "FusionInventory-Agent_v2.4.1"
10.225.213.43 - - [20/Aug/2018:13:22:58 +0200] "GET /ocsinventory/?action=getConfig&task[ESX]=2.3&machineid=MYCOMPUTER-MV-XP-2018-08-20-11-29-41 HTTP/1.1" 400 226 "-" "FusionInventory-Agent_v2.4.1"

But, why OCS Server responded with 400 status?
Thank you in advance!

**Comment by g-bougard** [comment]
The `400 Bad Request` error means OCS Server seems not to support the first XML POST request as PROLOG request. But we can't help more here.
The UserAgent set in conf is correct.
By the way, you should ask the question to OCS Server maintainers. Even if we know FusionInventory agent may be compatible with OCS, this is a point we can't guaranty, and we won't provide support for that.
I'm closing then the issue. If you obtain a response from OCS maintainers showing there's a real issue with the agent, feel free to reopen.

**Comment by g-bougard** [comment]
@proyectotau 
I realize one thing about your issue:
This is normal to obtain 400 status for request related to tasks other than Inventory as they are only supported by FusionInventory plugin for GLPI, and really not by OCS. If you only need to inventory your machine, you should just set "Inventory" as "tasks" parameter when installing or in registry after installing.

**Comment by proyectotau** [comment]
Thanks for mention!
I'll try
