### ISSUE TITLE
GPO deployment of 2.5.2 Agent

### ISSUE THREAD

**Issue by ghost** [fusioninventory/fusioninventory-agent-windows-installer#6]
Hello,

I'm testing several scripts on a computer before trying to deploy my GPO and the parameters are not working. I've integrated the .admx and .adml files and verified that the GPO can be deployed. We also have a certificate to verify our company.

When I try this script: https://raw.githubusercontent.com/fusioninventory/fusioninventory-agent/develop/contrib/windows/fusioninventory-agent-deployment.vbs

There is no error but the agent is obviously not installed.

When I try command line installation and indicate some of the parameters mentioned here: http://fusioninventory.org/documentation/agent/installation/windows/windows-installer-2.3.x-command-line.html

I get errors on my /server and /ca-cert-file options. However, I recognize that the mentioned page is not on the GitHub or the FusionInventory website and so might contain errors. 

When I try the scripts mentioned here: http://fusioninventory.org/documentation/agent/installation/windows/large_install.html

I get an error on /rpc-trust-localhost, and then no error when I remove this parameter, but no creation of the folder.

Can someone tell me if I'm doing something wrong or if these scripts just don't work for the latest version of the agent? Is it possible to do a command line installation in the second case? It seems to be the simplest option.

Many thanks,

**Comment by fle108** [comment]
do you have older agent install already present on machine ? maybe you can try with `Force = "Yes"` option in vbs file.
i have a similar problem , i don't find out how to update agents using gpo.

**Comment by ghost** [comment]
Hello,

No, I didn't have the older agent installed. In the end I went around the problem and just ended up deploying the agent with two GPOs, one with a .bat script. Maybe you can also use a .bat to update your agents?
